id: P65EC5C32
initial_creation_type: ocr
source_metadata:
  volumes:
    f3795d10e6b347608bb5fc0caa2f31a8:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ།
      total_pages: 1198
      volume_number: 97
